// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var App        = require("./app.js");
var Curry      = require("bs-platform/lib/js/curry.js");
var ReactDOMRe = require("reason-react/lib/js/src/reactDOMRe.js");

ReactDOMRe.renderToElementWithId(Curry._4(App.createElement("Welcome to Create Reason React App!"), /* [] */0, /* None */0, /* None */0, /* () */0), "root");

/*  Not a pure module */
